### ISSUE TITLE
[Bug] Holding space fires once, then spams

### ISSUE THREAD

**Issue by karnthis** [pecko95/EarthDefense#8]
Will get a gif when I get home, but currently if you hold the fire button (space) a single shot is fired, and then 4-5 seconds later a stream is fired until you overheat the gun.

**Comment by pstevovski** [comment]
Fixed by setting the `isSpaceDown` boolean to true the first time the user presses space and calls the function and then if `isSpaceDown` is still true, it returns (exits?) the function. On `keyup` resets the boolean to false. Commit: [668b24a](https://github.com/pecko95/EarthDefense/commit/668b24aa6cf4e9eb779b5dc1218a2ebb96cc6768)
